# Конфіг агента-клієнта SecMon

# Адреса сервера в локальній мережі
# Для тесту на одній машині: http://127.0.0.1:8000
# Для мережі (домашня, шлюз 192.168.0.1): IP ноутбука-сервера, напр. http://192.168.0.10:8000
server_url: "http://127.0.0.1:8000"

# Унікальний ідентифікатор цього вузла (можна лишити автогенерацію за hostname)
node_id: null   # null = візьме hostname автоматично

# Як часто слати heartbeat (сек)
heartbeat_interval: 15

# Як часто відправляти накопичені події на сервер (сек)
flush_interval: 10

# Шлях до Snort alert-логу (стандартний для Snort на Windows)
snort_log_path: "C:\\Snort\\log\\alert.ids"

# Які Event ID Windows Firewall відстежувати
# 5152/5157 - заблоковано, 5154/5156 - дозволено
firewall_event_ids: [5152, 5154, 5156, 5157]
